// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages, non_constant_identifier_names
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../entity/objectbox/basic_data.dart';
import '../../entity/objectbox/binding_carrier.dart';
import '../../entity/objectbox/receipt.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 1079460876789695771),
    name: 'ReceiptFoldDataStore',
    lastPropertyId: const obx_int.IdUid(14, 865216163863437120),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7076353075314851393),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3361745429023021481),
        name: 'sharedPreferences',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4651218740795652925),
        name: 'mobileBarcodeList_',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2520694363004643321),
        name: 'memberBarcodeList_',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 865216163863437120),
        name: 'invoiceWinningNumberList_',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 2034222204318544696),
    name: 'BindingCarrier',
    lastPropertyId: const obx_int.IdUid(8, 8519334872469532604),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1897620843358604272),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3256851776368946654),
        name: 'cardCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3095035128749522685),
        name: 'codeName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2256667638198429947),
        name: 'carrierId2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9148688283636984861),
        name: 'carrierName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5417635320909471955),
        name: 'awardMethod_',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4517677949696087609),
        name: 'claimPrizesMode_',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8519334872469532604),
        name: 'carrierId1',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 5915821701848146731),
    name: 'ReceiptDetail',
    lastPropertyId: const obx_int.IdUid(7, 7493369445859982677),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1200009136848675707),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8554044727299324460),
        name: 'sequenceNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9196544885097391989),
        name: 'itemDescription',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4521246199923451068),
        name: 'unitPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5927355935072080547),
        name: 'quantity',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3209699935624835784),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7493369445859982677),
        name: 'receiptHeaderId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 4523222621193976815),
        relationField: 'receiptHeader',
        relationTarget: 'ReceiptHeader',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(11, 3395674015362034533),
    name: 'ReceiptHeader',
    lastPropertyId: const obx_int.IdUid(18, 4138065004186626642),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4828911170551943432),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3224533860743586680),
        name: 'invoiceInstantDate',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 659599085903759163),
        name: 'receiptOrigin_',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3269122087557376834),
        name: 'totalAmount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 112443738462389278),
        name: 'invoiceStatus_',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 924194092909768197),
        name: 'invoiceNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1278340928639323896),
        name: 'currency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2671106379605076234),
        name: 'mainRemark',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1225805188588444484),
        name: 'randomNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4992767513731549882),
        name: 'sellerAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4397907342476918941),
        name: 'sellerBanId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1224440646464311486),
        name: 'sellerName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 7822271701814097432),
        name: 'carrierId2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6783187597617872860),
        name: 'carrierType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 4465963078262415409),
        name: 'carrierName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 4339058460845269235),
        name: 'prizeAmount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 251689247395111117),
        name: 'prizeInformation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 4138065004186626642),
        name: 'userNote',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'details',
        srcEntity: 'ReceiptDetail',
        srcField: '',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(11, 3395674015362034533),
    lastIndexId: const obx_int.IdUid(2, 4523222621193976815),
    lastRelationId: const obx_int.IdUid(2, 101432858550622428),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      5505250124291089406,
      5017302735504206538,
      469682224959179075,
      7318515650340693839,
      4654609903794412736,
      4379853736452989862,
      5890047482736057906,
    ],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      6374094936992944036,
      644658137325984466,
      8329668957335714307,
      7151058949220974079,
      5215725873732501237,
      7858979313028683402,
      6462471147409160452,
      7640648921046032902,
      5053825418459602766,
      6821240630428149853,
      3525934957851274299,
      2018121391193618844,
      4287342138468189985,
      996384980476623596,
      5464380158181594286,
      8278221487413507018,
      6545183710579149705,
      8476164686773279113,
      9028639119329108215,
      1442384411649667249,
      6525026840070316151,
      7940926623085835842,
      7365685869649243760,
      1219056189156906618,
      2338725937924056647,
      8821037750577305913,
      1256525593418484374,
      427290507430543661,
      3453549043708009172,
      8767718761700368095,
      4503324571875484729,
      1664656494839180139,
      8788418720583940369,
      1823545975760573855,
      2950153300282734300,
      5672548871981391401,
      8487289058236570204,
      1977957036178620861,
      8544868049799574241,
      3480044549119010118,
      6639404224385219183,
      6499456906514045838,
      2582247227820777396,
      741492209525468801,
      7790077907291895377,
      3876478732478884570,
      513372736905358400,
      3357024100148158619,
      2899039870363132980,
      2882114974898859672,
      147980446674785409,
      2733704370712255981,
      741687238455697168,
      4999662414911079696,
      7285041823731447673,
      6221208398690969964,
      22201425509190986,
      4517031380776021750,
      526705245235628296,
      2361324759088688370,
      2365403900961796983,
      8493866215845666895,
      232999675943555976,
      6557404173454567501,
      9179224666624794340,
      5511617383191854415,
      8811913128413835734,
      56989608117641563,
      1744495020872330462,
      1242260848511036382,
      5147140591276142375,
      840669712010072295,
      4878794624428492218,
      2911971028091379648,
    ],
    retiredRelationUids: const [3638656239345895125, 101432858550622428],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ReceiptFoldDataStore: obx_int.EntityDefinition<ReceiptFoldDataStore>(
      model: _entities[0],
      toOneRelations: (ReceiptFoldDataStore object) => [],
      toManyRelations: (ReceiptFoldDataStore object) => {},
      getId: (ReceiptFoldDataStore object) => object.id,
      setId: (ReceiptFoldDataStore object, int id) {
        object.id = id;
      },
      objectToFB: (ReceiptFoldDataStore object, fb.Builder fbb) {
        final sharedPreferencesOffset = object.sharedPreferences == null
            ? null
            : fbb.writeString(object.sharedPreferences!);
        final mobileBarcodeList_Offset = fbb.writeString(
          object.mobileBarcodeList_,
        );
        final memberBarcodeList_Offset = fbb.writeString(
          object.memberBarcodeList_,
        );
        final invoiceWinningNumberList_Offset = fbb.writeString(
          object.invoiceWinningNumberList_,
        );
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, sharedPreferencesOffset);
        fbb.addOffset(11, mobileBarcodeList_Offset);
        fbb.addOffset(12, memberBarcodeList_Offset);
        fbb.addOffset(13, invoiceWinningNumberList_Offset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final sharedPreferencesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final mobileBarcodeList_Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final memberBarcodeList_Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final invoiceWinningNumberList_Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final object = ReceiptFoldDataStore(
          sharedPreferences: sharedPreferencesParam,
          mobileBarcodeList_: mobileBarcodeList_Param,
          memberBarcodeList_: memberBarcodeList_Param,
          invoiceWinningNumberList_: invoiceWinningNumberList_Param,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    BindingCarrier: obx_int.EntityDefinition<BindingCarrier>(
      model: _entities[1],
      toOneRelations: (BindingCarrier object) => [],
      toManyRelations: (BindingCarrier object) => {},
      getId: (BindingCarrier object) => object.id,
      setId: (BindingCarrier object, int id) {
        object.id = id;
      },
      objectToFB: (BindingCarrier object, fb.Builder fbb) {
        final cardCodeOffset = fbb.writeString(object.cardCode);
        final codeNameOffset = fbb.writeString(object.codeName);
        final carrierId2Offset = fbb.writeString(object.carrierId2);
        final carrierNameOffset = fbb.writeString(object.carrierName);
        final awardMethod_Offset = fbb.writeString(object.awardMethod_);
        final claimPrizesMode_Offset = fbb.writeString(object.claimPrizesMode_);
        final carrierId1Offset = object.carrierId1 == null
            ? null
            : fbb.writeString(object.carrierId1!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, cardCodeOffset);
        fbb.addOffset(2, codeNameOffset);
        fbb.addOffset(3, carrierId2Offset);
        fbb.addOffset(4, carrierNameOffset);
        fbb.addOffset(5, awardMethod_Offset);
        fbb.addOffset(6, claimPrizesMode_Offset);
        fbb.addOffset(7, carrierId1Offset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final cardCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final codeNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final carrierId2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final carrierNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final awardMethod_Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final claimPrizesMode_Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final carrierId1Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final object = BindingCarrier(
          cardCode: cardCodeParam,
          codeName: codeNameParam,
          carrierId2: carrierId2Param,
          carrierName: carrierNameParam,
          awardMethod_: awardMethod_Param,
          claimPrizesMode_: claimPrizesMode_Param,
          carrierId1: carrierId1Param,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    ReceiptDetail: obx_int.EntityDefinition<ReceiptDetail>(
      model: _entities[2],
      toOneRelations: (ReceiptDetail object) => [object.receiptHeader],
      toManyRelations: (ReceiptDetail object) => {},
      getId: (ReceiptDetail object) => object.id,
      setId: (ReceiptDetail object, int id) {
        object.id = id;
      },
      objectToFB: (ReceiptDetail object, fb.Builder fbb) {
        final sequenceNumberOffset = fbb.writeString(object.sequenceNumber);
        final itemDescriptionOffset = fbb.writeString(object.itemDescription);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, sequenceNumberOffset);
        fbb.addOffset(2, itemDescriptionOffset);
        fbb.addFloat64(3, object.unitPrice);
        fbb.addFloat64(4, object.quantity);
        fbb.addFloat64(5, object.amount);
        fbb.addInt64(6, object.receiptHeader.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final sequenceNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final itemDescriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final unitPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final quantityParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = ReceiptDetail(
          sequenceNumber: sequenceNumberParam,
          itemDescription: itemDescriptionParam,
          unitPrice: unitPriceParam,
          quantity: quantityParam,
          amount: amountParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.receiptHeader.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.receiptHeader.attach(store);
        return object;
      },
    ),
    ReceiptHeader: obx_int.EntityDefinition<ReceiptHeader>(
      model: _entities[3],
      toOneRelations: (ReceiptHeader object) => [],
      toManyRelations: (ReceiptHeader object) => {
        obx_int.RelInfo<ReceiptDetail>.toOneBacklink(
          7,
          object.id,
          (ReceiptDetail srcObject) => srcObject.receiptHeader,
        ): object.details,
      },
      getId: (ReceiptHeader object) => object.id,
      setId: (ReceiptHeader object, int id) {
        object.id = id;
      },
      objectToFB: (ReceiptHeader object, fb.Builder fbb) {
        final receiptOrigin_Offset = fbb.writeString(object.receiptOrigin_);
        final invoiceStatus_Offset = object.invoiceStatus_ == null
            ? null
            : fbb.writeString(object.invoiceStatus_!);
        final invoiceNumberOffset = object.invoiceNumber == null
            ? null
            : fbb.writeString(object.invoiceNumber!);
        final currencyOffset = object.currency == null
            ? null
            : fbb.writeString(object.currency!);
        final mainRemarkOffset = object.mainRemark == null
            ? null
            : fbb.writeString(object.mainRemark!);
        final randomNumberOffset = object.randomNumber == null
            ? null
            : fbb.writeString(object.randomNumber!);
        final sellerAddressOffset = object.sellerAddress == null
            ? null
            : fbb.writeString(object.sellerAddress!);
        final sellerBanIdOffset = object.sellerBanId == null
            ? null
            : fbb.writeString(object.sellerBanId!);
        final sellerNameOffset = object.sellerName == null
            ? null
            : fbb.writeString(object.sellerName!);
        final carrierId2Offset = object.carrierId2 == null
            ? null
            : fbb.writeString(object.carrierId2!);
        final carrierTypeOffset = object.carrierType == null
            ? null
            : fbb.writeString(object.carrierType!);
        final carrierNameOffset = object.carrierName == null
            ? null
            : fbb.writeString(object.carrierName!);
        final prizeInformationOffset = object.prizeInformation == null
            ? null
            : fbb.writeString(object.prizeInformation!);
        final userNoteOffset = object.userNote == null
            ? null
            : fbb.writeString(object.userNote!);
        fbb.startTable(19);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.invoiceInstantDate);
        fbb.addOffset(2, receiptOrigin_Offset);
        fbb.addFloat64(3, object.totalAmount);
        fbb.addOffset(4, invoiceStatus_Offset);
        fbb.addOffset(5, invoiceNumberOffset);
        fbb.addOffset(6, currencyOffset);
        fbb.addOffset(7, mainRemarkOffset);
        fbb.addOffset(8, randomNumberOffset);
        fbb.addOffset(9, sellerAddressOffset);
        fbb.addOffset(10, sellerBanIdOffset);
        fbb.addOffset(11, sellerNameOffset);
        fbb.addOffset(12, carrierId2Offset);
        fbb.addOffset(13, carrierTypeOffset);
        fbb.addOffset(14, carrierNameOffset);
        fbb.addInt64(15, object.prizeAmount);
        fbb.addOffset(16, prizeInformationOffset);
        fbb.addOffset(17, userNoteOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final invoiceInstantDateParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final receiptOrigin_Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final totalAmountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final invoiceStatus_Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final invoiceNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final currencyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final mainRemarkParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final randomNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final sellerAddressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final sellerBanIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final sellerNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final carrierId2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final carrierTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final carrierNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final prizeAmountParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          34,
        );
        final prizeInformationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final userNoteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 38);
        final object = ReceiptHeader(
          invoiceInstantDate: invoiceInstantDateParam,
          receiptOrigin_: receiptOrigin_Param,
          totalAmount: totalAmountParam,
          invoiceStatus_: invoiceStatus_Param,
          invoiceNumber: invoiceNumberParam,
          currency: currencyParam,
          mainRemark: mainRemarkParam,
          randomNumber: randomNumberParam,
          sellerAddress: sellerAddressParam,
          sellerBanId: sellerBanIdParam,
          sellerName: sellerNameParam,
          carrierId2: carrierId2Param,
          carrierType: carrierTypeParam,
          carrierName: carrierNameParam,
          prizeAmount: prizeAmountParam,
          prizeInformation: prizeInformationParam,
          userNote: userNoteParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<ReceiptHeader>(
          object.details,
          store,
          obx_int.RelInfo<ReceiptDetail>.toOneBacklink(
            7,
            object.id,
            (ReceiptDetail srcObject) => srcObject.receiptHeader,
          ),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ReceiptFoldDataStore] entity fields to define ObjectBox queries.
class ReceiptFoldDataStore_ {
  /// See [ReceiptFoldDataStore.id].
  static final id = obx.QueryIntegerProperty<ReceiptFoldDataStore>(
    _entities[0].properties[0],
  );

  /// See [ReceiptFoldDataStore.sharedPreferences].
  static final sharedPreferences =
      obx.QueryStringProperty<ReceiptFoldDataStore>(_entities[0].properties[1]);

  /// See [ReceiptFoldDataStore.mobileBarcodeList_].
  static final mobileBarcodeList_ =
      obx.QueryStringProperty<ReceiptFoldDataStore>(_entities[0].properties[2]);

  /// See [ReceiptFoldDataStore.memberBarcodeList_].
  static final memberBarcodeList_ =
      obx.QueryStringProperty<ReceiptFoldDataStore>(_entities[0].properties[3]);

  /// See [ReceiptFoldDataStore.invoiceWinningNumberList_].
  static final invoiceWinningNumberList_ =
      obx.QueryStringProperty<ReceiptFoldDataStore>(_entities[0].properties[4]);
}

/// [BindingCarrier] entity fields to define ObjectBox queries.
class BindingCarrier_ {
  /// See [BindingCarrier.id].
  static final id = obx.QueryIntegerProperty<BindingCarrier>(
    _entities[1].properties[0],
  );

  /// See [BindingCarrier.cardCode].
  static final cardCode = obx.QueryStringProperty<BindingCarrier>(
    _entities[1].properties[1],
  );

  /// See [BindingCarrier.codeName].
  static final codeName = obx.QueryStringProperty<BindingCarrier>(
    _entities[1].properties[2],
  );

  /// See [BindingCarrier.carrierId2].
  static final carrierId2 = obx.QueryStringProperty<BindingCarrier>(
    _entities[1].properties[3],
  );

  /// See [BindingCarrier.carrierName].
  static final carrierName = obx.QueryStringProperty<BindingCarrier>(
    _entities[1].properties[4],
  );

  /// See [BindingCarrier.awardMethod_].
  static final awardMethod_ = obx.QueryStringProperty<BindingCarrier>(
    _entities[1].properties[5],
  );

  /// See [BindingCarrier.claimPrizesMode_].
  static final claimPrizesMode_ = obx.QueryStringProperty<BindingCarrier>(
    _entities[1].properties[6],
  );

  /// See [BindingCarrier.carrierId1].
  static final carrierId1 = obx.QueryStringProperty<BindingCarrier>(
    _entities[1].properties[7],
  );
}

/// [ReceiptDetail] entity fields to define ObjectBox queries.
class ReceiptDetail_ {
  /// See [ReceiptDetail.id].
  static final id = obx.QueryIntegerProperty<ReceiptDetail>(
    _entities[2].properties[0],
  );

  /// See [ReceiptDetail.sequenceNumber].
  static final sequenceNumber = obx.QueryStringProperty<ReceiptDetail>(
    _entities[2].properties[1],
  );

  /// See [ReceiptDetail.itemDescription].
  static final itemDescription = obx.QueryStringProperty<ReceiptDetail>(
    _entities[2].properties[2],
  );

  /// See [ReceiptDetail.unitPrice].
  static final unitPrice = obx.QueryDoubleProperty<ReceiptDetail>(
    _entities[2].properties[3],
  );

  /// See [ReceiptDetail.quantity].
  static final quantity = obx.QueryDoubleProperty<ReceiptDetail>(
    _entities[2].properties[4],
  );

  /// See [ReceiptDetail.amount].
  static final amount = obx.QueryDoubleProperty<ReceiptDetail>(
    _entities[2].properties[5],
  );

  /// See [ReceiptDetail.receiptHeader].
  static final receiptHeader =
      obx.QueryRelationToOne<ReceiptDetail, ReceiptHeader>(
        _entities[2].properties[6],
      );
}

/// [ReceiptHeader] entity fields to define ObjectBox queries.
class ReceiptHeader_ {
  /// See [ReceiptHeader.id].
  static final id = obx.QueryIntegerProperty<ReceiptHeader>(
    _entities[3].properties[0],
  );

  /// See [ReceiptHeader.invoiceInstantDate].
  static final invoiceInstantDate = obx.QueryIntegerProperty<ReceiptHeader>(
    _entities[3].properties[1],
  );

  /// See [ReceiptHeader.receiptOrigin_].
  static final receiptOrigin_ = obx.QueryStringProperty<ReceiptHeader>(
    _entities[3].properties[2],
  );

  /// See [ReceiptHeader.totalAmount].
  static final totalAmount = obx.QueryDoubleProperty<ReceiptHeader>(
    _entities[3].properties[3],
  );

  /// See [ReceiptHeader.invoiceStatus_].
  static final invoiceStatus_ = obx.QueryStringProperty<ReceiptHeader>(
    _entities[3].properties[4],
  );

  /// See [ReceiptHeader.invoiceNumber].
  static final invoiceNumber = obx.QueryStringProperty<ReceiptHeader>(
    _entities[3].properties[5],
  );

  /// See [ReceiptHeader.currency].
  static final currency = obx.QueryStringProperty<ReceiptHeader>(
    _entities[3].properties[6],
  );

  /// See [ReceiptHeader.mainRemark].
  static final mainRemark = obx.QueryStringProperty<ReceiptHeader>(
    _entities[3].properties[7],
  );

  /// See [ReceiptHeader.randomNumber].
  static final randomNumber = obx.QueryStringProperty<ReceiptHeader>(
    _entities[3].properties[8],
  );

  /// See [ReceiptHeader.sellerAddress].
  static final sellerAddress = obx.QueryStringProperty<ReceiptHeader>(
    _entities[3].properties[9],
  );

  /// See [ReceiptHeader.sellerBanId].
  static final sellerBanId = obx.QueryStringProperty<ReceiptHeader>(
    _entities[3].properties[10],
  );

  /// See [ReceiptHeader.sellerName].
  static final sellerName = obx.QueryStringProperty<ReceiptHeader>(
    _entities[3].properties[11],
  );

  /// See [ReceiptHeader.carrierId2].
  static final carrierId2 = obx.QueryStringProperty<ReceiptHeader>(
    _entities[3].properties[12],
  );

  /// See [ReceiptHeader.carrierType].
  static final carrierType = obx.QueryStringProperty<ReceiptHeader>(
    _entities[3].properties[13],
  );

  /// See [ReceiptHeader.carrierName].
  static final carrierName = obx.QueryStringProperty<ReceiptHeader>(
    _entities[3].properties[14],
  );

  /// See [ReceiptHeader.prizeAmount].
  static final prizeAmount = obx.QueryIntegerProperty<ReceiptHeader>(
    _entities[3].properties[15],
  );

  /// See [ReceiptHeader.prizeInformation].
  static final prizeInformation = obx.QueryStringProperty<ReceiptHeader>(
    _entities[3].properties[16],
  );

  /// See [ReceiptHeader.userNote].
  static final userNote = obx.QueryStringProperty<ReceiptHeader>(
    _entities[3].properties[17],
  );

  /// see [ReceiptHeader.details]
  static final details = obx.QueryBacklinkToMany<ReceiptDetail, ReceiptHeader>(
    ReceiptDetail_.receiptHeader,
  );
}
