// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages, non_constant_identifier_names
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../entity/objectbox/basic_data.dart';
import '../../entity/objectbox/binding_carrier.dart';
import '../../entity/objectbox/receipt.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 469682224959179075),
    name: 'BindingCarrier',
    lastPropertyId: const obx_int.IdUid(14, 5672548871981391401),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3453549043708009172),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8767718761700368095),
        name: 'cardCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4503324571875484729),
        name: 'codeName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1664656494839180139),
        name: 'carrierId2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8788418720583940369),
        name: 'carrierName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1823545975760573855),
        name: 'carrierId1',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2950153300282734300),
        name: 'awardMethod_',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 5672548871981391401),
        name: 'claimPrizesMode_',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 7318515650340693839),
    name: 'ReceiptDetail',
    lastPropertyId: const obx_int.IdUid(7, 2582247227820777396),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8487289058236570204),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1977957036178620861),
        name: 'sequenceNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8544868049799574241),
        name: 'itemDescription',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3480044549119010118),
        name: 'unitPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6639404224385219183),
        name: 'quantity',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6499456906514045838),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2582247227820777396),
        name: 'receiptHeaderId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 1429176585328373005),
        relationTarget: 'ReceiptHeader',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 1079460876789695771),
    name: 'ReceiptFoldDataStore',
    lastPropertyId: const obx_int.IdUid(14, 865216163863437120),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7076353075314851393),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3361745429023021481),
        name: 'sharedPreferences',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4651218740795652925),
        name: 'mobileBarcodeList_',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2520694363004643321),
        name: 'memberBarcodeList_',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 865216163863437120),
        name: 'invoiceWinningNumberList_',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 4654609903794412736),
    name: 'ReceiptFoldInfo',
    lastPropertyId: const obx_int.IdUid(3, 3876478732478884570),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 741492209525468801),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7790077907291895377),
        name: 'lastDataChangeUpdate',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3876478732478884570),
        name: 'lastTimeCloudBackup',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 4379853736452989862),
    name: 'ReceiptHeader',
    lastPropertyId: const obx_int.IdUid(24, 6557404173454567501),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 513372736905358400),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3357024100148158619),
        name: 'invoiceInstantDate',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2899039870363132980),
        name: 'totalAmount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2882114974898859672),
        name: 'invoiceNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 147980446674785409),
        name: 'currency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2733704370712255981),
        name: 'mainRemark',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 741687238455697168),
        name: 'randomNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4999662414911079696),
        name: 'sellerAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7285041823731447673),
        name: 'sellerBanId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6221208398690969964),
        name: 'sellerName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 22201425509190986),
        name: 'carrierId2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4517031380776021750),
        name: 'carrierType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 526705245235628296),
        name: 'carrierName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 2361324759088688370),
        name: 'prizeAmount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 2365403900961796983),
        name: 'prizeInformation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 8493866215845666895),
        name: 'userNote',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 232999675943555976),
        name: 'receiptOrigin_',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 6557404173454567501),
        name: 'invoiceStatus_',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'details',
        srcEntity: 'ReceiptDetail',
        srcField: '',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 5890047482736057906),
    name: 'UserInfo',
    lastPropertyId: const obx_int.IdUid(10, 2911971028091379648),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 9179224666624794340),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5511617383191854415),
        name: 'userId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8811913128413835734),
        name: 'userType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 56989608117641563),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1744495020872330462),
        name: 'phone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1242260848511036382),
        name: 'carrierId2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5147140591276142375),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 840669712010072295),
        name: 'menu',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4878794624428492218),
        name: 'emailChecked',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2911971028091379648),
        name: 'lastLoginDate',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(8, 5890047482736057906),
    lastIndexId: const obx_int.IdUid(1, 1429176585328373005),
    lastRelationId: const obx_int.IdUid(2, 101432858550622428),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [5505250124291089406, 5017302735504206538],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      6374094936992944036,
      644658137325984466,
      8329668957335714307,
      7151058949220974079,
      5215725873732501237,
      7858979313028683402,
      6462471147409160452,
      7640648921046032902,
      5053825418459602766,
      6821240630428149853,
      3525934957851274299,
      2018121391193618844,
      4287342138468189985,
      996384980476623596,
      5464380158181594286,
      8278221487413507018,
      6545183710579149705,
      8476164686773279113,
      9028639119329108215,
      1442384411649667249,
      6525026840070316151,
      7940926623085835842,
      7365685869649243760,
      1219056189156906618,
      2338725937924056647,
      8821037750577305913,
      1256525593418484374,
      427290507430543661,
    ],
    retiredRelationUids: const [3638656239345895125, 101432858550622428],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    BindingCarrier: obx_int.EntityDefinition<BindingCarrier>(
      model: _entities[0],
      toOneRelations: (BindingCarrier object) => [],
      toManyRelations: (BindingCarrier object) => {},
      getId: (BindingCarrier object) => object.id,
      setId: (BindingCarrier object, int id) {
        object.id = id;
      },
      objectToFB: (BindingCarrier object, fb.Builder fbb) {
        final cardCodeOffset = fbb.writeString(object.cardCode);
        final codeNameOffset = fbb.writeString(object.codeName);
        final carrierId2Offset = fbb.writeString(object.carrierId2);
        final carrierNameOffset = fbb.writeString(object.carrierName);
        final carrierId1Offset = object.carrierId1 == null
            ? null
            : fbb.writeString(object.carrierId1!);
        final awardMethod_Offset = fbb.writeString(object.awardMethod_);
        final claimPrizesMode_Offset = fbb.writeString(object.claimPrizesMode_);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, cardCodeOffset);
        fbb.addOffset(2, codeNameOffset);
        fbb.addOffset(3, carrierId2Offset);
        fbb.addOffset(4, carrierNameOffset);
        fbb.addOffset(5, carrierId1Offset);
        fbb.addOffset(12, awardMethod_Offset);
        fbb.addOffset(13, claimPrizesMode_Offset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final cardCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final codeNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final carrierId2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final carrierNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final awardMethod_Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final claimPrizesMode_Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final carrierId1Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = BindingCarrier(
          cardCode: cardCodeParam,
          codeName: codeNameParam,
          carrierId2: carrierId2Param,
          carrierName: carrierNameParam,
          awardMethod_: awardMethod_Param,
          claimPrizesMode_: claimPrizesMode_Param,
          carrierId1: carrierId1Param,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    ReceiptDetail: obx_int.EntityDefinition<ReceiptDetail>(
      model: _entities[1],
      toOneRelations: (ReceiptDetail object) => [object.receiptHeader],
      toManyRelations: (ReceiptDetail object) => {},
      getId: (ReceiptDetail object) => object.id,
      setId: (ReceiptDetail object, int id) {
        object.id = id;
      },
      objectToFB: (ReceiptDetail object, fb.Builder fbb) {
        final sequenceNumberOffset = fbb.writeString(object.sequenceNumber);
        final itemDescriptionOffset = fbb.writeString(object.itemDescription);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, sequenceNumberOffset);
        fbb.addOffset(2, itemDescriptionOffset);
        fbb.addFloat64(3, object.unitPrice);
        fbb.addFloat64(4, object.quantity);
        fbb.addFloat64(5, object.amount);
        fbb.addInt64(6, object.receiptHeader.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final sequenceNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final itemDescriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final unitPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final quantityParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = ReceiptDetail(
          sequenceNumber: sequenceNumberParam,
          itemDescription: itemDescriptionParam,
          unitPrice: unitPriceParam,
          quantity: quantityParam,
          amount: amountParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.receiptHeader.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.receiptHeader.attach(store);
        return object;
      },
    ),
    ReceiptFoldDataStore: obx_int.EntityDefinition<ReceiptFoldDataStore>(
      model: _entities[2],
      toOneRelations: (ReceiptFoldDataStore object) => [],
      toManyRelations: (ReceiptFoldDataStore object) => {},
      getId: (ReceiptFoldDataStore object) => object.id,
      setId: (ReceiptFoldDataStore object, int id) {
        object.id = id;
      },
      objectToFB: (ReceiptFoldDataStore object, fb.Builder fbb) {
        final sharedPreferencesOffset = object.sharedPreferences == null
            ? null
            : fbb.writeString(object.sharedPreferences!);
        final mobileBarcodeList_Offset = fbb.writeString(
          object.mobileBarcodeList_,
        );
        final memberBarcodeList_Offset = fbb.writeString(
          object.memberBarcodeList_,
        );
        final invoiceWinningNumberList_Offset = fbb.writeString(
          object.invoiceWinningNumberList_,
        );
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, sharedPreferencesOffset);
        fbb.addOffset(11, mobileBarcodeList_Offset);
        fbb.addOffset(12, memberBarcodeList_Offset);
        fbb.addOffset(13, invoiceWinningNumberList_Offset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final sharedPreferencesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final mobileBarcodeList_Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final memberBarcodeList_Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final invoiceWinningNumberList_Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final object = ReceiptFoldDataStore(
          sharedPreferences: sharedPreferencesParam,
          mobileBarcodeList_: mobileBarcodeList_Param,
          memberBarcodeList_: memberBarcodeList_Param,
          invoiceWinningNumberList_: invoiceWinningNumberList_Param,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    ReceiptFoldInfo: obx_int.EntityDefinition<ReceiptFoldInfo>(
      model: _entities[3],
      toOneRelations: (ReceiptFoldInfo object) => [],
      toManyRelations: (ReceiptFoldInfo object) => {},
      getId: (ReceiptFoldInfo object) => object.id,
      setId: (ReceiptFoldInfo object, int id) {
        object.id = id;
      },
      objectToFB: (ReceiptFoldInfo object, fb.Builder fbb) {
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.lastDataChangeUpdate);
        fbb.addInt64(2, object.lastTimeCloudBackup);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastDataChangeUpdateParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 6);
        final lastTimeCloudBackupParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 8);
        final object = ReceiptFoldInfo(
          lastDataChangeUpdate: lastDataChangeUpdateParam,
          lastTimeCloudBackup: lastTimeCloudBackupParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    ReceiptHeader: obx_int.EntityDefinition<ReceiptHeader>(
      model: _entities[4],
      toOneRelations: (ReceiptHeader object) => [],
      toManyRelations: (ReceiptHeader object) => {
        obx_int.RelInfo<ReceiptDetail>.toOneBacklink(
          7,
          object.id,
          (ReceiptDetail srcObject) => srcObject.receiptHeader,
        ): object.details,
      },
      getId: (ReceiptHeader object) => object.id,
      setId: (ReceiptHeader object, int id) {
        object.id = id;
      },
      objectToFB: (ReceiptHeader object, fb.Builder fbb) {
        final invoiceNumberOffset = object.invoiceNumber == null
            ? null
            : fbb.writeString(object.invoiceNumber!);
        final currencyOffset = object.currency == null
            ? null
            : fbb.writeString(object.currency!);
        final mainRemarkOffset = object.mainRemark == null
            ? null
            : fbb.writeString(object.mainRemark!);
        final randomNumberOffset = object.randomNumber == null
            ? null
            : fbb.writeString(object.randomNumber!);
        final sellerAddressOffset = object.sellerAddress == null
            ? null
            : fbb.writeString(object.sellerAddress!);
        final sellerBanIdOffset = object.sellerBanId == null
            ? null
            : fbb.writeString(object.sellerBanId!);
        final sellerNameOffset = object.sellerName == null
            ? null
            : fbb.writeString(object.sellerName!);
        final carrierId2Offset = object.carrierId2 == null
            ? null
            : fbb.writeString(object.carrierId2!);
        final carrierTypeOffset = object.carrierType == null
            ? null
            : fbb.writeString(object.carrierType!);
        final carrierNameOffset = object.carrierName == null
            ? null
            : fbb.writeString(object.carrierName!);
        final prizeInformationOffset = object.prizeInformation == null
            ? null
            : fbb.writeString(object.prizeInformation!);
        final userNoteOffset = object.userNote == null
            ? null
            : fbb.writeString(object.userNote!);
        final receiptOrigin_Offset = fbb.writeString(object.receiptOrigin_);
        final invoiceStatus_Offset = object.invoiceStatus_ == null
            ? null
            : fbb.writeString(object.invoiceStatus_!);
        fbb.startTable(25);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.invoiceInstantDate);
        fbb.addFloat64(2, object.totalAmount);
        fbb.addOffset(3, invoiceNumberOffset);
        fbb.addOffset(4, currencyOffset);
        fbb.addOffset(5, mainRemarkOffset);
        fbb.addOffset(6, randomNumberOffset);
        fbb.addOffset(7, sellerAddressOffset);
        fbb.addOffset(8, sellerBanIdOffset);
        fbb.addOffset(9, sellerNameOffset);
        fbb.addOffset(10, carrierId2Offset);
        fbb.addOffset(11, carrierTypeOffset);
        fbb.addOffset(12, carrierNameOffset);
        fbb.addInt64(13, object.prizeAmount);
        fbb.addOffset(14, prizeInformationOffset);
        fbb.addOffset(15, userNoteOffset);
        fbb.addOffset(22, receiptOrigin_Offset);
        fbb.addOffset(23, invoiceStatus_Offset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final invoiceInstantDateParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final receiptOrigin_Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 48, '');
        final totalAmountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final invoiceStatus_Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 50);
        final invoiceNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final currencyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final mainRemarkParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final randomNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final sellerAddressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final sellerBanIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final sellerNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final carrierId2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final carrierTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final carrierNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final prizeAmountParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          30,
        );
        final prizeInformationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final userNoteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final object = ReceiptHeader(
          invoiceInstantDate: invoiceInstantDateParam,
          receiptOrigin_: receiptOrigin_Param,
          totalAmount: totalAmountParam,
          invoiceStatus_: invoiceStatus_Param,
          invoiceNumber: invoiceNumberParam,
          currency: currencyParam,
          mainRemark: mainRemarkParam,
          randomNumber: randomNumberParam,
          sellerAddress: sellerAddressParam,
          sellerBanId: sellerBanIdParam,
          sellerName: sellerNameParam,
          carrierId2: carrierId2Param,
          carrierType: carrierTypeParam,
          carrierName: carrierNameParam,
          prizeAmount: prizeAmountParam,
          prizeInformation: prizeInformationParam,
          userNote: userNoteParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<ReceiptHeader>(
          object.details,
          store,
          obx_int.RelInfo<ReceiptDetail>.toOneBacklink(
            7,
            object.id,
            (ReceiptDetail srcObject) => srcObject.receiptHeader,
          ),
        );
        return object;
      },
    ),
    UserInfo: obx_int.EntityDefinition<UserInfo>(
      model: _entities[5],
      toOneRelations: (UserInfo object) => [],
      toManyRelations: (UserInfo object) => {},
      getId: (UserInfo object) => object.id,
      setId: (UserInfo object, int id) {
        object.id = id;
      },
      objectToFB: (UserInfo object, fb.Builder fbb) {
        final userIdOffset = object.userId == null
            ? null
            : fbb.writeString(object.userId!);
        final userTypeOffset = object.userType == null
            ? null
            : fbb.writeString(object.userType!);
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final phoneOffset = object.phone == null
            ? null
            : fbb.writeString(object.phone!);
        final carrierId2Offset = object.carrierId2 == null
            ? null
            : fbb.writeString(object.carrierId2!);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        final menuOffset = object.menu == null
            ? null
            : fbb.writeString(object.menu!);
        final emailCheckedOffset = object.emailChecked == null
            ? null
            : fbb.writeString(object.emailChecked!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, userIdOffset);
        fbb.addOffset(2, userTypeOffset);
        fbb.addOffset(3, nameOffset);
        fbb.addOffset(4, phoneOffset);
        fbb.addOffset(5, carrierId2Offset);
        fbb.addOffset(6, emailOffset);
        fbb.addOffset(7, menuOffset);
        fbb.addOffset(8, emailCheckedOffset);
        fbb.addInt64(9, object.lastLoginDate);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final userTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final phoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final carrierId2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final menuParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final emailCheckedParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final lastLoginDateParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final object = UserInfo(
          userId: userIdParam,
          userType: userTypeParam,
          name: nameParam,
          phone: phoneParam,
          carrierId2: carrierId2Param,
          email: emailParam,
          menu: menuParam,
          emailChecked: emailCheckedParam,
          lastLoginDate: lastLoginDateParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [BindingCarrier] entity fields to define ObjectBox queries.
class BindingCarrier_ {
  /// See [BindingCarrier.id].
  static final id = obx.QueryIntegerProperty<BindingCarrier>(
    _entities[0].properties[0],
  );

  /// See [BindingCarrier.cardCode].
  static final cardCode = obx.QueryStringProperty<BindingCarrier>(
    _entities[0].properties[1],
  );

  /// See [BindingCarrier.codeName].
  static final codeName = obx.QueryStringProperty<BindingCarrier>(
    _entities[0].properties[2],
  );

  /// See [BindingCarrier.carrierId2].
  static final carrierId2 = obx.QueryStringProperty<BindingCarrier>(
    _entities[0].properties[3],
  );

  /// See [BindingCarrier.carrierName].
  static final carrierName = obx.QueryStringProperty<BindingCarrier>(
    _entities[0].properties[4],
  );

  /// See [BindingCarrier.carrierId1].
  static final carrierId1 = obx.QueryStringProperty<BindingCarrier>(
    _entities[0].properties[5],
  );

  /// See [BindingCarrier.awardMethod_].
  static final awardMethod_ = obx.QueryStringProperty<BindingCarrier>(
    _entities[0].properties[6],
  );

  /// See [BindingCarrier.claimPrizesMode_].
  static final claimPrizesMode_ = obx.QueryStringProperty<BindingCarrier>(
    _entities[0].properties[7],
  );
}

/// [ReceiptDetail] entity fields to define ObjectBox queries.
class ReceiptDetail_ {
  /// See [ReceiptDetail.id].
  static final id = obx.QueryIntegerProperty<ReceiptDetail>(
    _entities[1].properties[0],
  );

  /// See [ReceiptDetail.sequenceNumber].
  static final sequenceNumber = obx.QueryStringProperty<ReceiptDetail>(
    _entities[1].properties[1],
  );

  /// See [ReceiptDetail.itemDescription].
  static final itemDescription = obx.QueryStringProperty<ReceiptDetail>(
    _entities[1].properties[2],
  );

  /// See [ReceiptDetail.unitPrice].
  static final unitPrice = obx.QueryDoubleProperty<ReceiptDetail>(
    _entities[1].properties[3],
  );

  /// See [ReceiptDetail.quantity].
  static final quantity = obx.QueryDoubleProperty<ReceiptDetail>(
    _entities[1].properties[4],
  );

  /// See [ReceiptDetail.amount].
  static final amount = obx.QueryDoubleProperty<ReceiptDetail>(
    _entities[1].properties[5],
  );

  /// See [ReceiptDetail.receiptHeader].
  static final receiptHeader =
      obx.QueryRelationToOne<ReceiptDetail, ReceiptHeader>(
        _entities[1].properties[6],
      );
}

/// [ReceiptFoldDataStore] entity fields to define ObjectBox queries.
class ReceiptFoldDataStore_ {
  /// See [ReceiptFoldDataStore.id].
  static final id = obx.QueryIntegerProperty<ReceiptFoldDataStore>(
    _entities[2].properties[0],
  );

  /// See [ReceiptFoldDataStore.sharedPreferences].
  static final sharedPreferences =
      obx.QueryStringProperty<ReceiptFoldDataStore>(_entities[2].properties[1]);

  /// See [ReceiptFoldDataStore.mobileBarcodeList_].
  static final mobileBarcodeList_ =
      obx.QueryStringProperty<ReceiptFoldDataStore>(_entities[2].properties[2]);

  /// See [ReceiptFoldDataStore.memberBarcodeList_].
  static final memberBarcodeList_ =
      obx.QueryStringProperty<ReceiptFoldDataStore>(_entities[2].properties[3]);

  /// See [ReceiptFoldDataStore.invoiceWinningNumberList_].
  static final invoiceWinningNumberList_ =
      obx.QueryStringProperty<ReceiptFoldDataStore>(_entities[2].properties[4]);
}

/// [ReceiptFoldInfo] entity fields to define ObjectBox queries.
class ReceiptFoldInfo_ {
  /// See [ReceiptFoldInfo.id].
  static final id = obx.QueryIntegerProperty<ReceiptFoldInfo>(
    _entities[3].properties[0],
  );

  /// See [ReceiptFoldInfo.lastDataChangeUpdate].
  static final lastDataChangeUpdate = obx.QueryIntegerProperty<ReceiptFoldInfo>(
    _entities[3].properties[1],
  );

  /// See [ReceiptFoldInfo.lastTimeCloudBackup].
  static final lastTimeCloudBackup = obx.QueryIntegerProperty<ReceiptFoldInfo>(
    _entities[3].properties[2],
  );
}

/// [ReceiptHeader] entity fields to define ObjectBox queries.
class ReceiptHeader_ {
  /// See [ReceiptHeader.id].
  static final id = obx.QueryIntegerProperty<ReceiptHeader>(
    _entities[4].properties[0],
  );

  /// See [ReceiptHeader.invoiceInstantDate].
  static final invoiceInstantDate = obx.QueryIntegerProperty<ReceiptHeader>(
    _entities[4].properties[1],
  );

  /// See [ReceiptHeader.totalAmount].
  static final totalAmount = obx.QueryDoubleProperty<ReceiptHeader>(
    _entities[4].properties[2],
  );

  /// See [ReceiptHeader.invoiceNumber].
  static final invoiceNumber = obx.QueryStringProperty<ReceiptHeader>(
    _entities[4].properties[3],
  );

  /// See [ReceiptHeader.currency].
  static final currency = obx.QueryStringProperty<ReceiptHeader>(
    _entities[4].properties[4],
  );

  /// See [ReceiptHeader.mainRemark].
  static final mainRemark = obx.QueryStringProperty<ReceiptHeader>(
    _entities[4].properties[5],
  );

  /// See [ReceiptHeader.randomNumber].
  static final randomNumber = obx.QueryStringProperty<ReceiptHeader>(
    _entities[4].properties[6],
  );

  /// See [ReceiptHeader.sellerAddress].
  static final sellerAddress = obx.QueryStringProperty<ReceiptHeader>(
    _entities[4].properties[7],
  );

  /// See [ReceiptHeader.sellerBanId].
  static final sellerBanId = obx.QueryStringProperty<ReceiptHeader>(
    _entities[4].properties[8],
  );

  /// See [ReceiptHeader.sellerName].
  static final sellerName = obx.QueryStringProperty<ReceiptHeader>(
    _entities[4].properties[9],
  );

  /// See [ReceiptHeader.carrierId2].
  static final carrierId2 = obx.QueryStringProperty<ReceiptHeader>(
    _entities[4].properties[10],
  );

  /// See [ReceiptHeader.carrierType].
  static final carrierType = obx.QueryStringProperty<ReceiptHeader>(
    _entities[4].properties[11],
  );

  /// See [ReceiptHeader.carrierName].
  static final carrierName = obx.QueryStringProperty<ReceiptHeader>(
    _entities[4].properties[12],
  );

  /// See [ReceiptHeader.prizeAmount].
  static final prizeAmount = obx.QueryIntegerProperty<ReceiptHeader>(
    _entities[4].properties[13],
  );

  /// See [ReceiptHeader.prizeInformation].
  static final prizeInformation = obx.QueryStringProperty<ReceiptHeader>(
    _entities[4].properties[14],
  );

  /// See [ReceiptHeader.userNote].
  static final userNote = obx.QueryStringProperty<ReceiptHeader>(
    _entities[4].properties[15],
  );

  /// See [ReceiptHeader.receiptOrigin_].
  static final receiptOrigin_ = obx.QueryStringProperty<ReceiptHeader>(
    _entities[4].properties[16],
  );

  /// See [ReceiptHeader.invoiceStatus_].
  static final invoiceStatus_ = obx.QueryStringProperty<ReceiptHeader>(
    _entities[4].properties[17],
  );

  /// see [ReceiptHeader.details]
  static final details = obx.QueryBacklinkToMany<ReceiptDetail, ReceiptHeader>(
    ReceiptDetail_.receiptHeader,
  );
}

/// [UserInfo] entity fields to define ObjectBox queries.
class UserInfo_ {
  /// See [UserInfo.id].
  static final id = obx.QueryIntegerProperty<UserInfo>(
    _entities[5].properties[0],
  );

  /// See [UserInfo.userId].
  static final userId = obx.QueryStringProperty<UserInfo>(
    _entities[5].properties[1],
  );

  /// See [UserInfo.userType].
  static final userType = obx.QueryStringProperty<UserInfo>(
    _entities[5].properties[2],
  );

  /// See [UserInfo.name].
  static final name = obx.QueryStringProperty<UserInfo>(
    _entities[5].properties[3],
  );

  /// See [UserInfo.phone].
  static final phone = obx.QueryStringProperty<UserInfo>(
    _entities[5].properties[4],
  );

  /// See [UserInfo.carrierId2].
  static final carrierId2 = obx.QueryStringProperty<UserInfo>(
    _entities[5].properties[5],
  );

  /// See [UserInfo.email].
  static final email = obx.QueryStringProperty<UserInfo>(
    _entities[5].properties[6],
  );

  /// See [UserInfo.menu].
  static final menu = obx.QueryStringProperty<UserInfo>(
    _entities[5].properties[7],
  );

  /// See [UserInfo.emailChecked].
  static final emailChecked = obx.QueryStringProperty<UserInfo>(
    _entities[5].properties[8],
  );

  /// See [UserInfo.lastLoginDate].
  static final lastLoginDate = obx.QueryIntegerProperty<UserInfo>(
    _entities[5].properties[9],
  );
}
