name: Build

on:
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          pub-cache: true

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang cmake ninja-build pkg-config libgtk-3-dev libstdc++-12-dev liblzma-dev

      - name: Build APK
        run: flutter build apk --split-per-abi

      - name: Sign APKs
        uses: ilharp/sign-android-release@v2
        id: sign_app
        with:
          releaseDir: build/app/outputs/flutter-apk
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: |
            build/app/outputs/flutter-apk/*-signed.apk
          if-no-files-found: error

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          pub-cache: true

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang cmake ninja-build pkg-config libgtk-3-dev libstdc++-12-dev liblzma-dev \
            libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
            libsecret-1-0 libsecret-1-dev \
            libwebkit2gtk-4.1-dev \
            p7zip-full wget locate
          sudo updatedb

      - name: Install Fastforge
        run: dart pub global activate fastforge

      - name: Install AppImage tool
        run: |
          wget -O appimagetool \
            https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool
          sudo mv appimagetool /usr/local/bin/appimagetool

      - name: Fastforge Build
        run: |
          ~/.pub-cache/bin/fastforge package \
            --platform linux \
            --targets zip,appimage

      - name: Patch AppImage
        run: |
          set -euo pipefail
          cd dist
          appimage="$(find . -name "*.AppImage" -type f | head -n1)"
          ./"$appimage" --appimage-extract >/dev/null
          rm -fv \
            squashfs-root/usr/lib/libgst*.so* \
            squashfs-root/usr/lib/libwebkit2gtk*.so* \
            squashfs-root/usr/lib/libjavascriptcoregtk*.so*
          ARCH=x86_64 appimagetool --no-appstream squashfs-root "$appimage"
          rm -rfv squashfs-root

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            dist/**
          if-no-files-found: error

  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          pub-cache: true

      - name: Install Fastforge
        run: dart pub global activate fastforge

      - name: Fastforge Build
        run: |
          $env:Path += ";$env:APPDATA\Pub\Cache\bin"
          fastforge package --platform windows --targets zip,exe

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            dist/**
          if-no-files-found: error
